In [19]:
import numpy as np


A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Choose an operation: 1. Addition, 2. Subtraction ,3. Multiplication, 4. Division, 5. Dot Product, 6. Transpose")
choice = int(input("Enter your choice (1-6): "))

if choice == 1:
    result = A + B
elif choice == 2:
    result = A - B
elif choice == 3:
    result = A * B
elif choice == 4:
    result = A / B
elif choice == 5:
    result = np.dot(A, B)
elif choice == 6:
    result = A.T
else:
    result = "Invalid choice"   
    
    
print("Result:\n", result)

Choose an operation: 1. Addition, 2. Subtraction ,3. Multiplication, 4. Division, 5. Dot Product, 6. Transpose
Result:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
